### ISSUE TITLE
dapr cli hangs after a successful dapr init

### ISSUE THREAD

**Issue by mcain12** [dapr/community#53]
upgrading to latest release.  I ran a dapr uninstall --all then reinstalled successfully, ran dapr init successfully. after that all dapr commands just hang.

**Comment by mcain12** [comment]
I am running on Windows 10 in shelf-host mode. Docker desktop is running correctly.

**Comment by mcain12** [comment]
I just deleted all the c:\dapr and .dapr directories and reinstalled following the directions on the website. here are the outputs of the dapr init and dapr --version commands.  the runtime version is n/a

C:\WINDOWS\system32>dapr init
Making the jump to hyperspace...
Downloading binaries and setting up components...
Downloaded binaries and completed components set up.
daprd binary has been installed to C:\Users\mcain\.dapr\bin.
dapr_placement container is running.
dapr_redis container is running.
dapr_zipkin container is running.
Use `docker ps` to check running containers.
Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

C:\WINDOWS\system32>dapr --version
CLI version: 1.1.0
Runtime version: n/a

C:\WINDOWS\system32>

**Comment by wcs1only** [comment]
I'm unable to reproduce this on my machine:
```
C:\Users\Charlie\components-contrib>dapr uninstall --all
Removing Dapr from your machine...
Removing directory: C:\Users\Charlie\.dapr\bin
Removing container: dapr_placement
Removing container: dapr_redis
Removing container: dapr_zipkin
Removing directory: C:\Users\Charlie\.dapr
Dapr has been removed successfully

C:\Users\Charlie\components-contrib>del C:\dapr
C:\dapr\*, Are you sure (Y/N)? y

C:\Users\Charlie\components-contrib>del C:\Users\Charlie\.dapr
Could Not Find C:\Users\Charlie\.dapr

C:\Users\Charlie\components-contrib>powershell -Command "iwr -useb https://raw.githubusercontent.com/dapr/cli/master/install/install.ps1 | iex"

Installing Dapr...
Creating c:\dapr directory
Downloading https://api.github.com/repos/dapr/cli/releases/assets/34341976 ...
Extracting c:\dapr\dapr_windows_amd64.zip...
CLI version: 1.1.0
Runtime version: n/a
Clean up c:\dapr\dapr_windows_amd64.zip...
Try to add c:\dapr to User Path Environment variable...
Skipping to add c:\dapr to User Path - C:\Users\Charlie\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Charlie\AppData\Local\Programs\Python\Python39\;C:\Users\Charlie\AppData\Local\Microsoft\WindowsApps;C:\Users\Charlie\go\bin;C:\Users\Charlie\AppData\Roaming\npm;C:\Users\Charlie\.dapr\bin;C:\Users\Charlie\.dotnet\tools;C:\Users\Charlie\go\bin;C:\dapr\;;C:\Users\Charlie\AppData\Local\Microsoft\WindowsApps

Dapr CLI is installed successfully.
To get started with Dapr, please visit https://docs.dapr.io/getting-started/ .
Ensure that Docker Desktop is set to Linux containers mode when you run Dapr in self hosted mode.

C:\Users\Charlie\components-contrib>dapr init
Making the jump to hyperspace...
Downloading binaries and setting up components...
Downloaded binaries and completed components set up.
daprd binary has been installed to C:\Users\Charlie\.dapr\bin.
dapr_placement container is running.
dapr_redis container is running.
dapr_zipkin container is running.
Use `docker ps` to check running containers.
Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

C:\Users\Charlie\components-contrib>dapr --version
CLI version: 1.1.0
Runtime version: 1.1.2

C:\Users\Charlie\components-contrib>echo %userprofile%
C:\Users\Charlie

C:\Users\Charlie\components-contrib>

```

What stands out in the terminal output you pasted:
```
daprd binary has been installed to C:\Users\mcain.dapr\bin.
```

There should be a '\' in there for "mcain\.dapr". Can you
```
echo %userprofile%
```
On your machine? That might give us some insights?

**Comment by mcain12** [comment]
This is what I have 


c:\Users\mcain>echo %userprofile%
C:\Users\mcain

**Comment by mcain12** [comment]
I just did the same process again and this time there is the \ in the output but same result...


c:\Users\mcain>dapr uninstall
Removing Dapr from your machine...
Removing directory: C:\Users\mcain\.dapr\bin
Removing container: dapr_placement
Dapr has been removed successfully

c:\Users\mcain>dapr init
Making the jump to hyperspace...
Downloading binaries and setting up components...
Downloaded binaries and completed components set up.
daprd binary has been installed to C:\Users\mcain\.dapr\bin.
dapr_placement container is running.
dapr_redis container is running.
dapr_zipkin container is running.
Use `docker ps` to check running containers.
Success! Dapr is up and running. To get started, go here: https://aka.ms/dapr-getting-started

c:\Users\mcain>dapr --version
CLI version: 1.1.0
Runtime version: n/a

**Comment by mcain12** [comment]
actually, what I just pasted is not what the output in the terminal window looks like:
![image](https://user-images.githubusercontent.com/73498199/117684195-c130d580-b182-11eb-9f9f-4c75dbb1044b.png)

**Comment by mcain12** [comment]
it throws this exception and hangs:

``
C:\Users\mcain>%userprofile%\.dapr\bin\daprd.exe -version
Exception 0xc0000005 0x0 0x7ff9c85b0fff 0x1dcc4280000
PC=0x1dcc4280000

syscall.Syscall(0x7ff9c7eaadc0, 0x3, 0xc0005979c8, 0x0, 0x800, 0x0, 0x0, 0x0)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/syscall_windows.go:330 +0xe9
golang.org/x/sys/windows._LoadLibraryEx(0xc0005979c8, 0x0, 0x800, 0xc, 0xc, 0x0)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/zsyscall_windows.go:2273 +0x96
golang.org/x/sys/windows.LoadLibraryEx(0x3d1bcfb, 0xb, 0x0, 0x800, 0xc000422b00, 0x30000, 0x5be42c0)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/zsyscall_windows.go:2269 +0x9f
golang.org/x/sys/windows.loadLibraryEx(0x3d1bcfb, 0xb, 0x2030001, 0x2030000, 0x20, 0x422269e)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/dll_windows.go:407 +0x66
golang.org/x/sys/windows.(*LazyDLL).Load(0xc000511500, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/dll_windows.go:242 +0xca
golang.org/x/sys/windows.(*LazyProc).Find(0xc000511560, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/dll_windows.go:305 +0xc5
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/dll_windows.go:323
golang.org/x/sys/windows.(*LazyProc).Call(0xc000511560, 0xc000502150, 0x5, 0x5, 0x4223768, 0x2030001, 0x20, 0x42285d2)
        C:/Users/runneradmin/go/pkg/mod/golang.org/x/sys@v0.0.0-20210225134936-a50acf3fe073/windows/dll_windows.go:347 +0x36
github.com/mattn/go-ieproxy.getUserConfigFromWindowsSyscall(0x0, 0x0, 0x0)
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/ieproxy_windows.go:79 +0xa6
github.com/mattn/go-ieproxy.writeConf()
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/ieproxy_windows.go:33 +0x66
sync.(*Once).doSlow(0x5c365f8, 0x3e473b0)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/sync/once.go:68 +0xf7
sync.(*Once).Do(...)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/sync/once.go:59
github.com/mattn/go-ieproxy.getConf(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/ieproxy_windows.go:23
github.com/mattn/go-ieproxy.GetConf(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/ieproxy.go:36
github.com/mattn/go-ieproxy.proxyMiddleman(0xc0008003e0)
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/proxyMiddleman_windows.go:12 +0x486
github.com/mattn/go-ieproxy.GetProxyFunc(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/mattn/go-ieproxy@v0.0.0-20190610004146-91bb50d98149/GetProxyFunc.go:10
github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClient(0xa4e8a9)
        C:/Users/runneradmin/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:208 +0x2d
github.com/Azure/azure-pipeline-go/pipeline.init()
        C:/Users/runneradmin/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:202 +0x29

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x5be2f60)
        C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:1169 +0x92
created by k8s.io/klog/v2.init.0
        C:/Users/runneradmin/go/pkg/mod/k8s.io/klog/v2@v2.4.0/klog.go:417 +0xe5

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00012a500)
        C:/Users/runneradmin/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xd4
created by go.opencensus.io/stats/view.init.0
        C:/Users/runneradmin/go/pkg/mod/go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x72
rax     0x7ff9b84245b8
rbx     0x7ff9b84245b6
rcx     0x41
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x69f8bff160
r8      0x0
r9      0x0
r10     0x0
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff9b84245b8
r15     0x7ff9c83b0000
rip     0x1dcc4280000
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b

C:\Users\mcain>
















































































































``

**Comment by wcs1only** [comment]
Ok, now we're getting somewhere. Do you have a proxy configured on your machine? 

https://docs.microsoft.com/en-us/troubleshoot/browsers/use-proxy-servers-with-ie

That might help us reproduce what you're experiencing.

**Comment by mcain12** [comment]
I do not have a proxy configured...

**Comment by wcs1only** [comment]
Hmmm, this smells like it could be the culprit:
https://github.com/mattn/go-ieproxy/issues/17

**Comment by mcain12** [comment]
I just chatted with my network administrator.  We use Cisco Umbrella, which sniffs out DNS calls.  Could that be interfering?


Thanks!

Mitch

_____________________________
Mitch Cain | CAI Software, LLC
O: 401-232-2600 ext. 3010 | C: 860-837-4604
[CAI_Software_Logo_2019_EmailSignatures]
www.caisoft.com<http://www.caisoft.com/>

Until further notice, CAI Software team members will be working remotely to support the national effort to reduce the spread of COVID-19.

IMPORTANT/CONFIDENTIAL: This message from CAI Software, LLC is privileged, confidential and exempt from disclosure under applicable law. If you are not the intended recipient (or authorized to act on behalf of the intended recipient) of this message, you may not disclose, forward, distribute, copy, or use this message or its contents. If you have received this communication in error, please notify us immediately by return e-mail and delete the original message from your e-mail system. Thank you.
